### ISSUE TITLE
wifi[:mac] returns nil when wifi is turned off causing hive to crash.

### ISSUE THREAD

**Issue by Asimk21** [bbc/device_api-android#82]
/home/hive/.rvm/gems/ruby-2.2.0/gems/device_api-android-1.2.1/lib/device_api/android/device.rb:270:in `wifi_mac_address': undefined method `[]' for nil:NilClass (NoMethodError)
        from /home/hive/.rvm/gems/ruby-2.2.0/bundler/gems/hive-runner-android-764db125667b/lib/hive/controller/android.rb:90:in `block in detect'
        from /home/hive/.rvm/gems/ruby-2.2.0/bundler/gems/hive-runner-android-764db125667b/lib/hive/controller/android.rb:86:in `each'
        from /home/hive/.rvm/gems/ruby-2.2.0/bundler/gems/hive-runner-android-764db125667b/lib/hive/controller/android.rb:86:in `detect'
        from /home/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.3/lib/hive/register.rb:60:in `block in check_controllers'
        from /home/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.3/lib/hive/register.rb:55:in `each'
        from /home/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.3/lib/hive/register.rb:55:in `check_controllers'
        from /home/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.3/lib/hive/register.rb:39:in `instantiate_controllers'
        from /home/hive/.rvm/gems/ruby-2.2.0/gems/hive-runner-2.0.3/bin/start_hive:115:in `<top (required)>'
        from /home/hive/.rvm/gems/ruby-2.2.0/bin/start_hive:23:in `load'
        from /home/hive/.rvm/gems/ruby-2.2.0/bin/start_hive:23:in `<main>'
        from /home/hive/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/hive/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by Asimk21** [comment]
Probably this is used in hivemind "macs: [device.wifi_mac_address]" on hive-07
